driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/omnibus-smartstack']

provisioner         :
    name            : ansible_push
    verbose         : "vvvv"
    playbook        : "provisioner/main.yml"
    ansible_config  : "provisioner/ansible.cfg"

platforms:
  - name: ubuntu-14.04
  - name: centos-7.0

suites:
  - name: default