---

- name: centos | Instal yum dependency
  yum:
    name="{{ item }}"
    update_cache="yes"
    state="present"
  with_items:
   - libcap-devel
   - "@Development tools"
  become: True

- name: use rvm install ruby-2.1.3
  shell: rvm install ruby-2.1.3 && rvm use ruby-2.1.3

- name: download fakeroot
  get_url: 
   url=ftp://ftp.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.20.2.orig.tar.bz2 
   dest=/tmp/fakeroot_1.20.2.orig.tar.bz2 

- name: unarchive fakeroot
  unarchive: 
    src=/tmp/fakeroot_1.20.2.orig.tar.bz2  
    dest=/tmp/
    copy=no

- name: centos | configure and install fakeroot
  shell: "./configure && make && make install"
  args:
    chdir: "/tmp/fakeroot-1.20.2"
  become: True

- set_fact:
    bundle_path: "bundle"

#git config --global user.email "you@example.com"    