---
- name: main | Include Ubuntu ruby 
  include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: main | Include centos ruby 
  include: centos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: main | Create omnibus directory
  file: 
    path="{{ item }}"
    state=directory
    owner="{{ omnibus_user }}"
    mode=0755
  with_items: omnibus_dir
  become: True


#old_hash="d7f7dd7e3ede3e323fc0e09381f16caf"
#new_hash="380df856e8f789c1af97d0da9a243769"
#sudo find / -name cacerts.rb  -type f  -exec sed -i -e 's/d7f7dd7e3ede3e323fc0e09381f16caf/380df856e8f789c1af97d0da9a243769/g' {} \;
- name: main | Gem default setting
  copy:
     content: "gem: --no-rdoc --no-ri"
     dest: "/home/{{ omnibus_user }}/.gemrc"

- name: main | Install bundle
  gem: 
    name=bundle
    state=latest

- name: main | Bundle install binstubs
  shell: "{{ bundle_path }} install --binstubs"
  args:
    chdir: "{{ omnibus_project_dir }}"

- name: main | omnibus build
  shell: "{{ bundle_path }} exec omnibus build {{ omnibus_project }}"
  args:
    chdir: "{{ omnibus_project_dir }}"
